# %YAML 1.2
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json  # yamllint disable-line
---
# version: "3.9"
name: ygg-gramps

networks:
  macvlan1:
    external: true

x-common: &common
  dns:
    - 10.4.21.34
    - 1.1.1.1
  dns_search:
    - ygg.nu
  restart: "no"
  stop_grace_period: 2m

x-env: &env
  TZ: UTC

x-tz: &tz /usr/share/zoneinfo/Etc/UTC:/etc/localtime:ro

services:
  gramps:
    <<: *common
    container_name: gramps
    cpu_count: 4
    depends_on:
      grampsweb-redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          # cpus: "4"
          memory: 1536M
    environment:
      <<: *env
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb-redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb-redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb-redis:6379/1
      GRAMPSWEB_TREE: "Gramps"
      GUNICORN_NUM_WORKERS: 3
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 90s
      test:
        [
          "CMD-SHELL",
          "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1",
        ]
      timeout: 5s
    hostname: gramps
    image: "ghcr.io/gramps-project/grampsweb:latest"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gramps.entrypoints: websecure
      traefik.http.routers.gramps.rule: "Host(`gramps.ebi.nu`)"
      traefik.http.routers.gramps.tls: "true"
      traefik.http.services.gramps.loadbalancer.server.port: 5000
    mac_address: "0e:be:00:da:00:87"
    networks:
      macvlan1:
        ipv4_address: 10.4.21.87
    volumes:
      - *tz
      - "/volume2/docker/gramps/cache:/app/cache"
      - "/volume2/docker/gramps/grampsdb:/root/.gramps/grampsdb"
      - "/volume2/docker/gramps/indexdir:/app/indexdir"
      - "/volume2/docker/gramps/media:/app/media"
      - "/volume2/docker/gramps/secret:/app/secret"
      - "/volume2/docker/gramps/thumbnail_cache:/app/thumbnail_cache"
      - "/volume2/docker/gramps/tmp:/tmp"
      - "/volume2/docker/gramps/users:/app/users"

  grampsweb-celery:
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2
    container_name: grampsweb-celery
    cpu_count: 2
    depends_on:
      gramps:
        condition: service_healthy
      grampsweb-redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          # cpus: "2"
          memory: 1024M
    environment:
      <<: *env
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb-redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb-redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb-redis:6379/1
      GRAMPSWEB_TREE: "Gramps"
      GUNICORN_NUM_WORKERS: 3
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 90s
      test:
        [
          "CMD-SHELL",
          "pgrep -f 'celery -A gramps_webapi.celery worker' >/dev/null || exit 1",
        ]
      timeout: 10s
    hostname: grampsweb-celery
    image: "ghcr.io/gramps-project/grampsweb:latest"
    mac_address: "0e:be:00:da:00:88"
    networks:
      macvlan1:
        ipv4_address: 10.4.21.88
    volumes:
      - *tz
      - "/volume2/docker/gramps/cache:/app/cache"
      - "/volume2/docker/gramps/grampsdb:/root/.gramps/grampsdb"
      - "/volume2/docker/gramps/indexdir:/app/indexdir"
      - "/volume2/docker/gramps/media:/app/media"
      - "/volume2/docker/gramps/secret:/app/secret"
      - "/volume2/docker/gramps/thumbnail_cache:/app/thumbnail_cache"
      - "/volume2/docker/gramps/tmp:/tmp"
      - "/volume2/docker/gramps/users:/app/users"

  grampsweb-redis:
    <<: *common
    container_name: grampsweb-redis
    cpu_count: 2
    deploy:
      resources:
        limits:
          # cpus: "2"
          memory: 1024M
    environment:
      <<: *env
    healthcheck:
      interval: 30s
      retries: 3
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
    hostname: grampsweb-redis
    image: "docker.io/library/redis:7.2.4-alpine"
    mac_address: "0e:be:00:da:00:89"
    networks:
      macvlan1:
        ipv4_address: 10.4.21.89
    sysctls:
      net.core.somaxconn: 512
    volumes:
      - *tz
      - /volume2/docker/gramps/redis:/data
