---
esphome:
  area: Kitchen
  friendly_name: esp-6
  min_version: 2025.2.0
  name: esp-6

esp32:
  board: esp32-c6-devkitm-1
  flash_size: 4MB
  framework:
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
    type: esp-idf
    version: 5.3.1
  variant: esp32c6

external_components:
  - source:
      ref: adc_oneshot
      type: git
      url: https://github.com/lboue/esphome
    components: [adc]
    refresh: 0s

api:
  encryption:
    key: !secret api_6
  reboot_timeout: 0s

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_6

logger:

wifi:
  domain: .int.tnt.photo
  password: !secret wifi_password
  ssid: !secret wifi_ssid

binary_sensor:
  - platform: status
    device_class: connectivity
    entity_category: diagnostic
    id: system_status
    name: Node Status
  - platform: gpio
    filters:
      - delayed_off: 10ms
    name: Button
    pin:
      ignore_strapping_warning: true
      inverted: true
      mode:
        input: true
        pullup: true
      number: GPIO9
  - platform: gpio
    filters:
      - delayed_off: 1000ms
      - delayed_on: 10ms
    name: Moisture hit
    pin:
      inverted: true
      mode:
        input: true
        pullup: true
      number: GPIO2

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

esp32_ble_tracker:
  scan_parameters:
    active: true

light:
  - platform: status_led
    entity_category: diagnostic
    id: led
    name: LED
    pin: GPIO7
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    effects:
      - addressable_rainbow:
      - flicker:
      - random:
    #      - strobe:
    id: rgb
    is_rgbw: true
    name: RGB
    num_leds: 1 #4
    pin: GPIO20
    power_supply: rgbpwr
    restore_mode: RESTORE_DEFAULT_OFF
    rgb_order: GRB
#    rmt_channel: 1

power_supply:
  - id: rgbpwr
    enable_on_boot: true
    enable_time: 10ms
    keep_on_time: 10ms
    pin: GPIO19

remote_transmitter:
  carrier_duty_percent: 50%
  pin: GPIO3

sensor:
  - platform: uptime
    device_class: duration
    entity_category: diagnostic
    icon: mdi:timer-outline
    id: uptime_s
    name: Uptime
    state_class: total_increasing
    update_interval: 300s
  - platform: wifi_signal
    accuracy_decimals: 0
    device_class: signal_strength
    entity_category: diagnostic
    icon: mdi:wifi-strength-3
    id: wifi_signal_db
    name: Wi-Fi Signal
    state_class: measurement
    unit_of_measurement: dBm
    update_interval: 60s
  - platform: adc
    accuracy_decimals: 3
    filters:
      - multiply: 3.3
      - sliding_window_moving_average:
          send_every: 30
          window_size: 30
    id: porta_g1
    name: Moisture
    pin:
      mode:
        input: true
        pullup: true
      number: GPIO1
    unit_of_measurement: V
    update_interval: 2s
