---
esphome:
  area: Hall
  friendly_name: esp-3
  min_version: 2025.2.0
  name: esp-3
  platformio_options:
    board_build.f_cpu: 240000000L
    board_build.mcu: esp32s3

esp32:
  board: m5stack-atoms3
  flash_size: 8MB
  framework:
    platform_version: 6.9.0
    type: esp-idf
    version: 5.3.1
  variant: esp32s3

api:
  encryption:
    key: !secret api_3
  reboot_timeout: 0s

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_3

logger:

wifi:
  domain: .int.tnt.photo
  password: !secret wifi_password
  ssid: !secret wifi_ssid

binary_sensor:
  - platform: status
    device_class: connectivity
    entity_category: diagnostic
    id: system_status
    name: Node Status
  - platform: gpio
    filters:
      - delayed_off: 10ms
    name: Button
    pin:
      inverted: true
      mode:
        input: true
        pullup: true
      number: GPIO41
  - platform: gpio
    filters:
      - delayed_off: 1000ms
      - delayed_on: 10ms
    name: Illuminance hit
    pin:
      inverted: true
      mode:
        input: true
        pullup: true
      number: GPIO2

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

esp32_ble_tracker:
  scan_parameters:
    active: true

light:
  - platform: esp32_rmt_led_strip
    chipset: ws2812
    id: led
    name: LED
    num_leds: 4
    pin: GPIO35
    restore_mode: RESTORE_DEFAULT_OFF
    rgb_order: GRB
#    rmt_channel: 2

remote_transmitter:
  carrier_duty_percent: 50%
  pin: GPIO4

sensor:
  - platform: uptime
    device_class: duration
    entity_category: diagnostic
    icon: mdi:timer-outline
    id: uptime_s
    name: Uptime
    state_class: total_increasing
    update_interval: 300s
  - platform: wifi_signal
    accuracy_decimals: 0
    device_class: signal_strength
    entity_category: diagnostic
    icon: mdi:wifi-strength-3
    id: wifi_signal_db
    name: Wi-Fi Signal
    state_class: measurement
    unit_of_measurement: dBm
    update_interval: 60s
  - platform: adc
    device_class: illuminance
    filters:
      - lambda: |-
          return 200 - (x / 10000.0) * 2000000.0;
    id: porta_g1
    name: Illuminance
    pin:
      mode:
        input: true
        pullup: true
      number: GPIO1
    unit_of_measurement: "lx"
    update_interval: 1s
