[platformio]
test_dir = /dev/null
src_dir = .

[env:lora-1]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_flags = -I ../include
lib_deps =
    bblanchon/ArduinoJson
    knolleary/PubSubClient
    jgromes/RadioLib
