# %YAML 1.2
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json  # yamllint disable-line
---
# version: "3.9"
name: ygg

x-common: &common
  restart: unless-stopped
  stop_grace_period: 1m

x-env: &env
  TZ: "UTC"

x-tz: &tz "/usr/share/zoneinfo/Etc/UTC:/etc/localtime:ro"

services:
  alloy:
    <<: *common
    cap_add:
      - SYS_ADMIN
      - SYSLOG
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    container_name: alloy
    cpu_count: 1
    deploy:
      resources:
        limits:
          memory: 1536M
    devices:
      - /dev/kmsg
    environment:
      <<: *env
      ALLOY_DEPLOY_MODE: "docker"
      ALLOY_HOST: "yggdrasil"
      LOKI_URL: "https://loki.ebi.nu/loki/api/v1/push"
      PROM_URL: "https://prometheus.ebi.nu/api/v1/write"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: alloy
    image: "docker.io/grafana/alloy:latest"
    volumes:
      - *tz
      - "/:/rootfs:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/dev/mapper/:/dev/mapper:ro"
      - "/volume2/docker/loki/config.alloy:/etc/alloy/config.alloy:ro"
      - "/proc:/rootproc:ro"
      - "/sys:/sys:ro"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/volume2/@docker:/var/lib/docker:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  watchtower:
    <<: *common
    container_name: watchtower
    cpu_count: 1
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      <<: *env
      NO_COLOR: "true"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LOG_FORMAT: "JSON"
    hostname: watchtower
    image: "docker.io/nickfedor/watchtower:latest"
    privileged: true
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - *tz
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/volume2/docker/watchtower/config.json:/config.json"
